stb_ds: fix undeclared identifier stbds_BB
The error

In file included from main.c:3:
./stb_ds.h:944:15: error: use of undeclared identifier 'stbds_BB'
  944 |     t->seed = stbds_BB;
      |               ^
1 error generated.

Looks like it's a typo that was introduced by accident in
recent commit 758b6365aea39b45fc807175c7a444e427690722